### ISSUE TITLE
report_taskview() incorrect order and header

### ISSUE THREAD

**Issue by konradmayer** [emilyriederer/projmgr#19]
When I include report_taskview() in rmarkdown, all the categories (not started, in progress, done) are at the top of the taskview followed by the issues in random order. Works correctly in viz_taskview() and I only checked for issues and not for milestones.

**Comment by konradmayer** [comment]
Refers to https://github.com/emilyriederer/projmgr/issues/14#issuecomment-457887785

**Comment by emilyriederer** [comment]
@konradmayer  Does this happen just in the RStudio markdown preview or in the browser too? If both, may I ask what browser you are using? I also get this within RStudio (as I don't think its previewer supports CSS grid) but it worked for me on the Chrome / Safari / Firefox browser versions I have. Thanks!

**Comment by konradmayer** [comment]
You are right! It was just the RStudio preview - works fine on Chrome and Firefox here too. The spacing between the individual boxes feels a bit big for me, maybe it would be a helpful thing for new users to indicate the possibility to add custom CSS in Rmarkdown within the report vignette (a link to an external ressource is probably more than enough in this regard).

**Comment by emilyriederer** [comment]
Thanks for the feedback and sorry for the very belated reply! I opened a new issue (#22) to remember that a vignette should be added for this. That's a great idea!
