### ISSUE TITLE
Wrong order of arguments

### ISSUE THREAD

**Issue by konradmayer** [emilyriederer/projmgr#9]
In the vignette the arguments to `post_plan()` are shown in the reverse order:
https://github.com/emilyriederer/projmgr/blob/a2985b1a7cd8a2dfb975d6ae1abad67e57c42bc8/vignettes/analysis-projects.Rmd#L44

**Comment by emilyriederer** [comment]
@konradmayer Fixed! Thank you so much for taking the time to report this -- I really appreciate it!
